version: '3.8'

services:
  app:
    container_name: falabella-proxy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FALABELLA_ENDPOINT=${FALABELLA_ENDPOINT}
      - FALABELLA_USER_ID=${FALABELLA_USER_ID}
      - FALABELLA_API_KEY=${FALABELLA_API_KEY}
    ports:
      - "80:80"
    restart: unless-stopped
